export const adminRoutes = [
  {
    path: "",
    title: "Administration",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ['User', 'Admin'],
    submenu: []
  },
  {
    path: '',
    title: 'Dashboard',
    iconType: 'material-icons-outlined',
    icon: 'dashboard',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin', 'Manager'],
    submenu: [
      {
        path: '/admin/dashboard/main',
        title: 'LMS Dashboard',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: [],
      },
      {
        path: '/admin/dashboard/analysis',
        title: 'Admin Panel',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: [],
      },
    ],
  },
  {
    path: '/users/list',
    title: 'Manage Users',
    iconType: 'material-icons-outlined',
    icon: 'supervised_user_circle',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },
  {
    path: '/admin/permissions/list',
    title: 'User Permissions',
    iconType: 'material-icons-outlined',
    icon: 'vpn_lock',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [],
  },
];

// Conditionally injected by RouteService for Admin (by role) OR anyone holding the
// Role:TalentPartner permission (by permission, not role — see route.service.ts). `role: ['All']`
// here because visibility is already fully decided by that injection condition, not by the
// caller's actual UserRoleEnum value (a Talent Partner's own role is typically 'User', not 'Admin').
export const manageUsersRoutes = [
    {
    path: "",
    title: "Talent Partner Tools",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ['User', 'Admin'],
    submenu: []
  },
  {
    path: '/users/list',
    title: 'Tech Talents',
    iconType: 'material-icons-outlined',
    icon: 'supervised_user_circle',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },
];
