export const welcomeRoutes = [
  {
    path: '/dashboard',
    title: 'My Dashboard',
    iconType: 'material-icons-outlined',
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['User', 'All'],
    submenu: [],
  },
  // {
  //   path: '/app/welcome',
  //   title: 'Welcome',
  //   iconType: 'material-icons-outlined',
  //   icon: 'insights',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['All'],
  //   submenu: [],
  // },
  {
    path: '/app/standard-quiz',
    title: 'Browse Quizzes',
    iconType: 'material-icons-outlined',
    icon: 'extension',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },
  {
    path: '/select-job-role',
    title: 'Explore Tech Roles',
    iconType: 'material-icons-outlined',
    icon: 'school',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },
  {
    path: '/select-subject',
    title: 'Explore Subjects',
    iconType: 'material-icons-outlined',
    icon: 'library_books',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },
  {
    // Public global XP leaderboard — standalone route (see codemerit's app.routes.ts), not
    // scoped to any job role, so it belongs in the base nav rather than under a specific
    // dashboard/role area.
    path: '/leaderboard',
    title: 'Leaderboard',
    iconType: 'material-icons-outlined',
    icon: 'leaderboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  }
];
