export const welcomeRoutes = [
  {
    path: '/dashboard',
    title: 'My Dashboard',
    iconType: 'material-icons-outlined',
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['User'],
    submenu: [],
  },
  {
    path: '',
    title: 'Explore',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },
  {
    path: '/select-job-role',
    title: 'Explore Job Roles',
    iconType: 'material-icons-outlined',
    icon: 'school',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },
  {
    path: '/select-subject',
    title: 'Explore Subjects',
    iconType: 'material-icons-outlined',
    icon: 'library_books',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },
  {
    path: '/app/standard-quiz',
    title: 'Practice Quizzes',
    iconType: 'material-icons-outlined',
    icon: 'extension',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },
  {
    path: '',
    title: 'My Assessments',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['User'],
    submenu: [],
  },
  {
    path: '/app/my-quizzes',
    title: 'My Quizzes',
    iconType: 'material-icons-outlined',
    icon: 'quiz',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['User'],
    submenu: [],
  },
  // interviewRoutes (Schedule Mock Interview, My Interviews) is unioned in right after this
  // array in route.service.ts — it continues this same "My Assessments" group without its own
  // header. See interview.routes.ts.
];
